name: Zola on GitHub Pages

on: 
 push:
  branches:
   - initial_website

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout initial_website
      uses: actions/checkout@v3.0.0
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.17.2
      env:
        repo-token: ${{ secrets.GITHUB_TOKEN }}