name: Zola on GitHub Pages
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout @ master
        uses: actions/checkout@master
      - name: build_and_deploy zola-deploy-action@v0.15.2
        uses: shalzz/zola-deploy-action@v0.15.2
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.WEBSITE_TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          # TOKEN: ${{ secrets.GITHUB_TOKEN }}
