name: Zola on GitHub Pages
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.WEBSITE_TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          # TOKEN: ${{ secrets.GITHUB_TOKEN }}
