name: Zola on GitHub Pages from master with theme

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages
  workflow_dispatch:
  repository_dispatch:
    types: [doxygen-deploy]


jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v3.0.0

    - name: Get Doxygen Documentation
      run: |
        git clone -b gh-pages --single-branch https://github.com/pauleaster/encrypted_buffer_cpp.git temp_docs
        echo "*************************************"
        echo "ls -al temp_docs"
        ls -al temp_docs
        echo "*************************************"
        echo "ls -al temp_docs/project_name.txt"
        ls -al temp_docs/project_name.txt
        echo "*************************************"
        echo "Calculating PROJECT_NAME"
        PROJECT_NAME=$(cat temp_docs/project_name.txt)
        echo "PROJECT_NAME: $PROJECT_NAME"
        echo "*************************************"
        mkdir -p "./static/$PROJECT_NAME"
        cp -r temp_docs/* "./static/$PROJECT_NAME"
        rm -rf temp_docs
        pwd
        echo "*************************************"
        echo "ls -al ./static"
        ls -al ./static
        echo "*************************************"
        echo "ls -al ./static/$PROJECT_NAME"
        ls -al "./static/$PROJECT_NAME"
        echo "PROJECT_NAME: $PROJECT_NAME"
        echo "*************************************"

    # - name: Build and deploy
    #   uses: shalzz/zola-deploy-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
